import os
import time
import httpx
import google.generativeai as genai
from fastapi import APIRouter
from prisma import Prisma
from dotenv import load_dotenv

load_dotenv()

router = APIRouter()
genai.configure(api_key=os.getenv("GEMINI_API_KEY"))

# --- 1. REAL WEATHER TOOL ---


def get_real_weather(city: str):
    """Checks the REAL current weather using Open-Meteo."""
    city = city.lower().strip()
    locations = {
        "lahore": {"lat": 31.5497, "long": 74.3436},
        "karachi": {"lat": 24.8607, "long": 67.0011},
        "islamabad": {"lat": 33.6844, "long": 73.0479},
        "peshawar": {"lat": 34.0151, "long": 71.5249},
        "multan": {"lat": 30.1575, "long": 71.5249},
        "murree": {"lat": 33.9078, "long": 73.3906},
    }

    if city not in locations:
        return f"Assume the weather in {city} is mild (20°C)."

    loc = locations[city]
    try:
        url = f"https://api.open-meteo.com/v1/forecast?latitude={loc['lat']}&longitude={loc['long']}&current=temperature_2m"
        response = httpx.get(url, timeout=3.0)
        data = response.json()
        temp = data['current']['temperature_2m']

        condition = "Mild"
        if temp < 15:
            condition = "Cold/Winter"
        if temp > 30:
            condition = "Hot/Summer"

        return f"Weather in {city.title()}: {temp}°C ({condition})."
    except:
        return f"Could not check weather for {city}. Assume it is Pleasant."


# --- 2. ROBUST CHAT LOGIC ---
tools = [get_real_weather]

# The "Unkillable" List
MODELS_TO_TRY = [
    'models/gemini-flash-lite-latest',
    'models/gemini-2.0-flash-lite-001',
    'models/gemini-1.5-flash',
    'models/gemini-pro'
]


@router.post("/chat")
async def chat_with_clerk(user_message: str):
    db = Prisma()

    text = "I'm having trouble thinking right now."
    ui_action = "NONE"
    used_model = "None"  # Track which model wins

    try:
        # A. LOAD INVENTORY
        await db.connect()
        products = await db.product.find_many()

        inventory_text = "CURRENT INVENTORY:\n"
        if not products:
            inventory_text += "(Inventory Empty)"
        else:
            for p in products:
                inventory_text += f"- ID: {p.id} | Name: {p.name} | Price: ${p.price} | Min Price: ${p.min_price} | Desc: {p.description}\n"

        # B. TRY MODELS ONE BY ONE
        response = None
        last_error = None

        for model_name in MODELS_TO_TRY:
            try:
                # Debug print to show effort
                print(f"🔄 Trying model: {model_name}...")

                model = genai.GenerativeModel(
                    model_name=model_name,
                    tools=tools,
                    system_instruction=f"""
                    You are 'The Clerk' for HDwear.
                    {inventory_text}
                    RULES:
                    1. **Weather:** If user asks about weather/travel, ASK "Which city?" first. Then call `get_real_weather`.
                    2. **Inventory:** Only recommend items from the list above.
                    3. **UI Actions:**
                       - Sort: [ACTION:SORT_PRICE_ASC] or [ACTION:SORT_PRICE_DESC]
                       - Buy/Add: [ACTION:ADD_TO_CART:PRODUCT_ID] (e.g. [ACTION:ADD_TO_CART:12])
                       - View Cart/Checkout: [ACTION:NAVIGATE_CART]  <-- ADD THIS LINE
                    4. **Haggling:** Never sell below 'Min Price'. If deal reached, say "Deal!".
                    """
                )

                chat = model.start_chat(enable_automatic_function_calling=True)
                response = chat.send_message(user_message)

                # IF WE REACH HERE, IT WORKED!
                text = response.text
                used_model = model_name
                print(f"✅ SUCCESS! Response generated by: {used_model}")
                break
            except Exception as e:
                last_error = e
                print(f"❌ Failed {model_name}: {e}")
                continue

        if not response:
            print(f"------------ ALL MODELS FAILED: {last_error} ------------")
            text = "My brain is a bit overloaded. Please wait 30 seconds and try again!"

    except Exception as e:
        print(f"------------ SYSTEM ERROR: {e} ------------")

    finally:
        if db.is_connected():
            await db.disconnect()

    # C. PARSE ACTION
    if "[ACTION:" in text:
        import re
        match = re.search(r"\[ACTION:([\w_:]+)\]", text)
        if match:
            ui_action = match.group(1)
            text = text.replace(match.group(0), "")

    # Return the model name so you can debug in frontend if needed
    return {"text": text, "action": ui_action, "debug_model": used_model}
